index:
    path: /
    controller: App\Controller\ActionController::index
create-action:
    path: /actions/new
    controller: App\Controller\ActionController::create
    methods: POST
new-action:
    path: /actions/new
    controller: App\Controller\ActionController::new
    methods: GET
show-actions:
    path: /actions
    controller: App\Controller\ActionController::show
    methods: GET
delete-action:
    path: /actions/delete/{id}
    controller: App\Controller\ActionController::delete
    methods: DELETE
    requirements:
        id: '\d+'
edit-action:
    path: /actions/{id}
    controller: App\Controller\ActionController::single
    methods: GET
    requirements:
        id: '\d+'
update-action:
    path: /actions/edit/{id}
    controller: App\Controller\ActionController::update
    methods: PUT
api_buildings:
    path: /api/buildings
    controller: App\Controller\BuildingApiController::index
    methods: GET
api_apartments_by_building:
    path: /api/buildings/{id}/apartments
    controller: App\Controller\BuildingApiController::showApartments
    methods: GET
    requirements:
        id: '\d+'
api_rooms_by_apartment:
    path: /api/apartments/{id}/rooms
    controller: App\Controller\ApartmentApiController::showRooms
    methods: GET
    requirements:
        id: '\d+'
